services:
  - type: web
    name: scops-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: APP_NAME
        value: SCOPS
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:ZnBJCGQaYI2PsZ3MwjR79s4P8BhObG/NIaWqi9nfXaM=
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: scops-scops.g.aivencloud.com
      - key: DB_PORT
        value: 25096
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_Uspn0KVspCi4ArdDuX0
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        value: "false"
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
- key: CLOUDINARY_CLOUD_NAME

  value: o2aqdium

- key: CLOUDINARY_API_KEY

  value: 925919952815821

- key: CLOUDINARY_API_SECRET

  value: TqiJYnYkZWbDvB082nJGDLtD3Yk
